name: "Changed Files"
description: "Detects changed files in a PR or push"

inputs:
  filters:
    description: "Glob patterns to filter changed files"
    required: false
    default: "**/*"
  base-sha:
    description: "Base SHA for comparison"
    required: false
  head-sha:
    description: "Head SHA for comparison"
    required: false
  token:
    description: "GitHub Token"
    required: false

outputs:
  changed-files:
    description: "JSON containing all changed files by category"
    value: ${{ steps.changed-files.outputs.changed-files }}
  any-changed:
    description: "Boolean indicating if any files changed"
    value: ${{ steps.changed-files.outputs.any-changed }}

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.13.3

    - name: Run changed files script
      id: changed-files
      shell: bash
      run: python3 ${{ github.action_path }}/src/main.py
      env:
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_FILTERS: ${{ inputs.filters }}
        INPUT_BASE_SHA: ${{ inputs.base-sha }}
        INPUT_HEAD_SHA: ${{ inputs.head-sha }}
